-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 13:18:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema acreditacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `acreditacion` ;

-- -----------------------------------------------------
-- Schema acreditacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acreditacion` DEFAULT CHARACTER SET utf8 ;
USE `acreditacion` ;

-- -----------------------------------------------------
-- Table `acreditacion`.`administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`administradores` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`administradores` (
  `id_administrador` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id del Administrador',
  `primerNombreAdministrador` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Primer Nombre del Adminsitrador',
  `segundoNombreAdministrador` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'Segundo Nombre del Administrador',
  `primerApellidoAdministrador` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Primer Apellido del Administrador',
  `segundoApellidoAdministrador` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'Segundo Apellido del Administrador',
  `numCedulaCiudadaniaAdministrador` INT(11) NOT NULL COMMENT 'Numero de Cedula de Ciudadania del Administrador',
  `direccionCorreoElectronico` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Direccion de Correo Electronico del Adminsitrador',
  `usuario` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nombre de usuario del Administrador',
  `contrasena` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Contraseña del Administrador',
  `contrasena_rdel` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Contraseña en Rjindael para Recordar',
  `habilitado` CHAR(1) CHARACTER SET 'utf8' NOT NULL DEFAULT '0' COMMENT 'Si esta habilitado para ingresar al sistema.',
  `nivel` CHAR(1) CHARACTER SET 'utf8' NOT NULL DEFAULT '0' COMMENT 'Nivel de Acceso del Administrador',
  `logged_in` CHAR(1) CHARACTER SET 'utf8' NOT NULL DEFAULT '0' COMMENT 'Si esta en 0 no esta en sesion, si esta en 1 esta en sesion',
  `ext` INT(11) NOT NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB
AUTO_INCREMENT = 100000026
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla de Administradores';


-- -----------------------------------------------------
-- Table `acreditacion`.`token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`token` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`token` (
  `id_token` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Token del usuario',
  `token` VARCHAR(1000) NOT NULL COMMENT 'String del token',
  `verificado` CHAR(1) NOT NULL DEFAULT '0' COMMENT '0 Si no esta verificado, 1 si esta verificado',
  `usuario_token` VARCHAR(1000) NOT NULL COMMENT 'Usuario del Token',
  `fechaActivacion` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_token`))
ENGINE = InnoDB
AUTO_INCREMENT = 761
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id del Usuario',
  `usuario` VARCHAR(1000) NOT NULL COMMENT 'Usuario que inicia sesion en la aplicacion',
  `contrasena` VARCHAR(1000) NOT NULL COMMENT 'Contraseña con que se valida el login',
  `contrasena_rdel` VARCHAR(1000) NOT NULL COMMENT 'Contraseña en Rijndael para recordar.',
  `logged_in` CHAR(1) NULL DEFAULT '0' COMMENT 'Si esta en 0 no esta en sesion, si esta en 1 esta en sesion',
  `token_id_token` INT(11) NULL DEFAULT NULL COMMENT 'Id de la tabla Token',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_token1_idx` (`token_id_token` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_token1`
    FOREIGN KEY (`token_id_token`)
    REFERENCES `acreditacion`.`token` (`id_token`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 761
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`organizaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`organizaciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`organizaciones` (
  `id_organizacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Registro de la Organizacion',
  `nombreOrganizacion` VARCHAR(1000) NOT NULL COMMENT 'Nombre de la Organizacion',
  `numNIT` VARCHAR(1000) NOT NULL COMMENT 'Numero NIT de la Organizacion',
  `sigla` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'Sigla de la organizacion',
  `primerNombreRepLegal` VARCHAR(1000) NOT NULL COMMENT 'Primer Nombre del Representante Legal',
  `segundoNombreRepLegal` VARCHAR(1000) NULL DEFAULT 'No Tiene' COMMENT 'Segundo Nombre del Representante Legal',
  `primerApellidoRepLegal` VARCHAR(1000) NOT NULL COMMENT 'Primer Apellido del Representante Legal',
  `segundoApellidoRepLegal` VARCHAR(1000) NULL DEFAULT 'No Tiene' COMMENT 'Segundo Apellido del Representante Legal',
  `direccionCorreoElectronicoOrganizacion` VARCHAR(1000) NOT NULL COMMENT 'Direccion de Correo Electronico de Contacto de la organizacion',
  `direccionCorreoElectronicoRepLegal` VARCHAR(1000) NOT NULL COMMENT 'Direccion de Correo Electronico de Contacto del representante legal',
  `primerNombrePersona` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Primer Nombre de la persona que Ingreso la informacion',
  `primerApellidoPersona` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Primer Apellido de la persona que ingreso la informacion',
  `imagenOrganizacion` VARCHAR(1000) NULL DEFAULT 'default.png' COMMENT 'Logo / Imagen de la organizacion',
  `firmaRepLegal` VARCHAR(1000) NULL DEFAULT 'default.png',
  `contrasena_firma` VARCHAR(1000) NULL DEFAULT NULL,
  `camaraComercio` VARCHAR(1000) NULL DEFAULT 'default.pdf',
  `firmaCert` VARCHAR(1000) NULL DEFAULT 'default.png',
  `personaCert` VARCHAR(1000) NULL DEFAULT 'Nombre Persona',
  `cargoCert` VARCHAR(1000) NULL DEFAULT 'Representante Legal',
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `usuarios_id_usuario` INT(11) NULL DEFAULT NULL COMMENT 'Id usuario de la tabla de usuarios',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_organizacion`),
  INDEX `fk_registro_usuarios_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_registro_usuarios`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `acreditacion`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 761
DEFAULT CHARACTER SET = utf8
COMMENT = 'Primer registro de las organizaciones';


-- -----------------------------------------------------
-- Table `acreditacion`.`antecedentesacademicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`antecedentesacademicos` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`antecedentesacademicos` (
  `id_antecedentesAcademicos` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id tabla Antecedentes Academicos',
  `descripcionProceso` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT 'Descripción cualitativa de los procesos de formación que ha realizado',
  `justificacion` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT 'Justificacion del Proceso del Antecedente',
  `objetivos` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT 'Objetivo del Proceso del Antecedente',
  `metodologia` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT 'Metodologia del proceso Antecedente Academico',
  `materialDidactico` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT 'Material Didactivo usado para llevar a cabo el Proceso Antecedente Academico',
  `bibliografia` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT 'Bilbiografia del proceso Antecedente Academico',
  `duracionCurso` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Tiempo en duracion del Curso',
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizacion',
  `idSolicitud` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id_antecedentesAcademicos`),
  INDEX `fk_antecedentesAcademicos_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_antecedentesAcademicos_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 940
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Formulario # 4 de SIA Antecedentes Academicos.';


-- -----------------------------------------------------
-- Table `acreditacion`.`archivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`archivos` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`archivos` (
  `id_archivo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Archivo',
  `tipo` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Tipo de Archivo: Carta, Certificacion, Imagen',
  `nombre` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nombre del Archivo subido por el cliente',
  `id_formulario` INT(11) NOT NULL COMMENT 'id del formulario donde se sube el archivo',
  `id_registro` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizacion',
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id_archivo`),
  INDEX `fk_archivos_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_archivos_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13780
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Archivos donde se guardan los archvios subidos por el usuario';


-- -----------------------------------------------------
-- Table `acreditacion`.`archivosdocente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`archivosdocente` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`archivosdocente` (
  `id_archivosDocente` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Archivos Docente',
  `tipo` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Tipo de Archivo del Docente',
  `nombre` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nombre del archivo del Docente',
  `observacionArchivo` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT 'Ninguna',
  `docentes_id_docente` INT(11) NOT NULL COMMENT 'FK Id_Docente',
  PRIMARY KEY (`id_archivosDocente`),
  INDEX `fk_archivosDocente_docentes1_idx` (`docentes_id_docente` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14742
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Archivos del docente ';


-- -----------------------------------------------------
-- Table `acreditacion`.`docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`docentes` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`docentes` (
  `id_docente` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Docente',
  `primerNombreDocente` VARCHAR(1000) NOT NULL COMMENT 'Primer Nombre del Docente',
  `segundoNombreDocente` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Segundo Nombre del Docente',
  `primerApellidoDocente` VARCHAR(1000) NOT NULL COMMENT 'Primer Apellido del Docente',
  `segundoApellidoDocente` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Segundo Apellido del Docente',
  `numCedulaCiudadaniaDocente` VARCHAR(1000) NOT NULL COMMENT 'Numero de Cedula de Ciudadania del Docente',
  `profesion` VARCHAR(1000) NOT NULL COMMENT 'Profesion del Docente',
  `horaCapacitacion` VARCHAR(1000) NOT NULL COMMENT 'Horas que tiene el Docente Capacitando',
  `valido` CHAR(1) NOT NULL DEFAULT '0' COMMENT 'Si el docente es Valido 1, Si el Docente no es Valido 0',
  `observacion` VARCHAR(1000) NULL DEFAULT NULL,
  `observacionAnterior` VARCHAR(1000) NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NULL DEFAULT NULL COMMENT 'FK Id_Organizacion',
  `asignado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_docente`),
  INDEX `fk_docentes_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_docentes_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1539
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario #9 SIA';


-- -----------------------------------------------------
-- Table `acreditacion`.`informeactividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`informeactividades` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`informeactividades` (
  `id_informeActividades` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL COMMENT 'Fecha cuando se realizo el Curso',
  `fechaFin` DATE NOT NULL COMMENT 'Fecha de Guardado del Curso',
  `departamento` VARCHAR(1000) NOT NULL,
  `municipio` VARCHAR(1000) NOT NULL,
  `duracion` INT(11) NOT NULL COMMENT 'Duracion del Curso en Horas',
  `intencionalidad` JSON NOT NULL,
  `cursos` JSON NOT NULL COMMENT 'Tipo del Curso realizado',
  `modalidades` JSON NOT NULL COMMENT 'Nombre del Curso Impartido',
  `totalAsistentes` INT(11) NOT NULL COMMENT 'Numero de Asistentes al Curso',
  `mujeres` INT(11) NOT NULL COMMENT 'Numero de mujeres',
  `hombres` INT(11) NOT NULL COMMENT 'Numero de Hombres',
  `noBinario` INT(11) NOT NULL COMMENT 'Numero de Hombres',
  `archivoAsistentes` VARCHAR(1000) NULL DEFAULT NULL,
  `archivoAsistencia` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'Creado',
  `docentes_id_docente` INT(11) NOT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  PRIMARY KEY (`id_informeActividades`),
  INDEX `fk_informeActividades_docentes1_idx` (`docentes_id_docente` ASC) VISIBLE,
  INDEX `fk_informeActividades_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_informeActividades_docentes1`
    FOREIGN KEY (`docentes_id_docente`)
    REFERENCES `acreditacion`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informeActividades_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 316
DEFAULT CHARACTER SET = utf8
COMMENT = 'Se guardan los Informes de las Actividades de las Organizaciones.';


-- -----------------------------------------------------
-- Table `acreditacion`.`asistentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`asistentes` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`asistentes` (
  `id_asistentes` INT(11) NOT NULL AUTO_INCREMENT,
  `primerApellidoAsistente` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Primer Apellido del Asistente',
  `segundoApellidoAsistente` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Segundo Nombre del Asistente',
  `primerNombreAsistente` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Primer Nombre del Asistente',
  `segundoNombreAsistente` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Segundo Nombre del Asistente',
  `numeroDocumentoAsistente` FLOAT NULL DEFAULT NULL COMMENT 'Numero del Documento del Asistente',
  `numNITOrganizacion` FLOAT NULL DEFAULT NULL COMMENT 'NIT de la Organizacion a la que pertenece el Asistente',
  `nombreOrganizacion` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Nombre de la Organizacion a la que pertenece el Asistente',
  `departamentoResidencia` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Direccion donde vive el asistente',
  `municipioResidencia` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Minicipio donde vive el asistente',
  `telefono` FLOAT NULL DEFAULT NULL COMMENT 'Direccion de correo electronico del Asistente',
  `correoElectronico` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Edad del Asistente',
  `edad` INT(11) NULL DEFAULT NULL COMMENT 'Sexo del Asistente',
  `genero` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Nivel de Formacion del Asistente',
  `escolaridad` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Rol del Asistente en la Organizacion',
  `enfoqueDiferencial` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Es Cabeza de Familia?',
  `condicionVulnerabilidad` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Es Indigena?',
  `discapacidad` VARCHAR(1000) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL COMMENT 'Tiene Discapacidad?',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `informeActividades_id_informeActividades` INT(11) NOT NULL COMMENT 'FK del Id_informeActividades',
  PRIMARY KEY (`id_asistentes`),
  INDEX `fk_asistentes_informeActividades1_idx` (`informeActividades_id_informeActividades` ASC) VISIBLE,
  CONSTRAINT `fk_asistentes_informeActividades1`
    FOREIGN KEY (`informeActividades_id_informeActividades`)
    REFERENCES `acreditacion`.`informeactividades` (`id_informeActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9368
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Información de los Asistentes del Curso';


-- -----------------------------------------------------
-- Table `acreditacion`.`bateriaobservaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`bateriaobservaciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`bateriaobservaciones` (
  `id_bateriaObservaciones` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(1000) CHARACTER SET 'latin1' NOT NULL,
  `titulo` VARCHAR(1000) CHARACTER SET 'latin1' NOT NULL,
  `observacion` VARCHAR(1000) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_bateriaObservaciones`))
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `acreditacion`.`certificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`certificaciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`certificaciones` (
  `id_certificacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Certificacion',
  `numeroCertificado` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'Numero Aleatorio del Certificado',
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nombre del Certificado',
  `informeActividades_id_informeActividades` INT(11) NOT NULL,
  PRIMARY KEY (`id_certificacion`),
  INDEX `fk_certificaciones_informeActividades1_idx` (`informeActividades_id_informeActividades` ASC) VISIBLE,
  CONSTRAINT `fk_certificaciones_informeActividades1`
    FOREIGN KEY (`informeActividades_id_informeActividades`)
    REFERENCES `acreditacion`.`informeactividades` (`id_informeActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Certificaciones del Sistema para informes de Actividades';


-- -----------------------------------------------------
-- Table `acreditacion`.`certificadoexistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`certificadoexistencia` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`certificadoexistencia` (
  `id_certificadoExistencia` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id tabla Registro educativo',
  `entidad` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL COMMENT 'Tipo de educacion Select  Option: Educacion para el trabajo y el desarrollo humano\\\\nFormal\\\\nInformal',
  `fechaExpedicion` DATE NOT NULL COMMENT 'Fecha en la que se expide la resolucion',
  `departamento` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL COMMENT 'Numero de la resolucion',
  `municipio` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nombre del Programa Texto',
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizaciones',
  `idSolicitud` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id_certificadoExistencia`),
  INDEX `fk_registroEducativoProgramas_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_registroEducativoProgramas_organizaciones10`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 159
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Formulario # 3 de SIA Registro Educativo de Programas.';


-- -----------------------------------------------------
-- Table `acreditacion`.`correosregistro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`correosregistro` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`correosregistro` (
  `id_correosRegistro` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `de` VARCHAR(45) NULL DEFAULT NULL,
  `para` VARCHAR(45) NULL DEFAULT NULL,
  `cc` VARCHAR(45) NULL DEFAULT NULL,
  `cco` VARCHAR(45) NULL DEFAULT NULL,
  `asunto` LONGTEXT NULL DEFAULT NULL,
  `cuerpo` JSON NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `adjunto` LONGTEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  `error` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_correosRegistro`))
ENGINE = InnoDB
AUTO_INCREMENT = 2770
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`datosaplicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`datosaplicacion` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`datosaplicacion` (
  `id_datosAplicacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id tabla Datos Aplicacion',
  `urlAplicacion` VARCHAR(1000) NOT NULL COMMENT 'URL donde se encuentra la aplicacion virtual',
  `usuarioAplicacion` VARCHAR(1000) NOT NULL COMMENT 'Nombre de usuario de la aplicacion Virtual',
  `contrasenaAplicacion` VARCHAR(1000) NOT NULL COMMENT 'Contraseña de la aplicacion Virtual de la Organizacion',
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_datosAplicacion`),
  INDEX `fk_datosAplicacion_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_datosAplicacion_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 376
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario #10 SIA';


-- -----------------------------------------------------
-- Table `acreditacion`.`datosbasicosprogramas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`datosbasicosprogramas` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`datosbasicosprogramas` (
  `id_datosBasicosProgramas` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id tabla datos basicos programas',
  `objetivos` LONGTEXT NOT NULL COMMENT 'Objetivos del Programa',
  `metodologia` LONGTEXT NOT NULL COMMENT 'Metodologia del Programa',
  `materialDidactico` LONGTEXT NOT NULL COMMENT 'Material Diactivo del Programa',
  `bibliografia` LONGTEXT NOT NULL COMMENT 'Bibliografia que usa el programa',
  `duracionCurso` LONGTEXT NOT NULL COMMENT 'Duracion del Curso',
  `eticaValoresPrincipios` LONGTEXT NULL DEFAULT NULL,
  `solidaridad` LONGTEXT NULL DEFAULT NULL,
  `economia` LONGTEXT NULL DEFAULT NULL,
  `economiaSolidaria` LONGTEXT NULL DEFAULT NULL,
  `asosiatividadEmprendimiento` LONGTEXT NULL DEFAULT NULL,
  `organizacionSolidaria` LONGTEXT NULL DEFAULT NULL,
  `trabajoEquipo` LONGTEXT NULL DEFAULT NULL,
  `educacionSolidaria` LONGTEXT NULL DEFAULT NULL,
  `responsabilidadSocial` LONGTEXT NULL DEFAULT NULL,
  `medioAmbiente` LONGTEXT NULL DEFAULT NULL,
  `contextoEconomicoSocial` LONGTEXT NULL DEFAULT NULL,
  `necesidadesSerHumano` LONGTEXT NULL DEFAULT NULL,
  `porqueFomentar` LONGTEXT NULL DEFAULT NULL,
  `principiosValoresFines` LONGTEXT NULL DEFAULT NULL,
  `marcoNormativo` LONGTEXT NULL DEFAULT NULL,
  `tiposOrganizacionesEconomiaSolidaria` LONGTEXT NULL DEFAULT NULL,
  `antecedentesHistoricos` LONGTEXT NULL DEFAULT NULL,
  `caracteristicasEconomicas` LONGTEXT NULL DEFAULT NULL,
  `estructuraInterna` LONGTEXT NULL DEFAULT NULL,
  `marcoJuridicoAplicable` LONGTEXT NULL DEFAULT NULL,
  `fundamentosAdministrativos` LONGTEXT NULL DEFAULT NULL,
  `orientacionElaboracionEstatutos` LONGTEXT NULL DEFAULT NULL,
  `unidadAdministrativa` LONGTEXT NULL DEFAULT NULL,
  `superintendencia` LONGTEXT NULL DEFAULT NULL,
  `fondoGarantias` LONGTEXT NULL DEFAULT NULL,
  `consejoNacional` LONGTEXT NULL DEFAULT NULL,
  `fondoNacional` LONGTEXT NULL DEFAULT NULL,
  `mesasRegionales` LONGTEXT NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizacion',
  PRIMARY KEY (`id_datosBasicosProgramas`),
  INDEX `fk_datosBasicosProgramas_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_datosBasicosProgramas_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 219
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`datosenlinea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`datosenlinea` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`datosenlinea` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id tabla Datos Aplicacion',
  `nombreHerramienta` VARCHAR(1000) NOT NULL COMMENT 'Nombre de la herramienta a utilizar',
  `descripcionHerramienta` VARCHAR(1000) NOT NULL COMMENT 'Descripcion aplicación en linea que utilizara para el desarrollo del proceso formativo',
  `fecha` DATETIME NOT NULL,
  `aceptacion` VARCHAR(20) NOT NULL COMMENT 'Acepta las recomendaciones',
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datosAplicacion_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_datosAplicacion_organizaciones10`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 251
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario #10 SIA';


-- -----------------------------------------------------
-- Table `acreditacion`.`datosmodalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`datosmodalidades` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`datosmodalidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreModalidad` VARCHAR(255) NULL DEFAULT NULL,
  `aceptarModalidad` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datosModalidades_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_datosModalidades_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 121
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `acreditacion`.`datosprogramas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`datosprogramas` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`datosprogramas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrePrograma` VARCHAR(255) NULL DEFAULT NULL,
  `aceptarPrograma` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datosProgramas_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_datosProgramas_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1039
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`departamentos` (
  `id_departamento` INT(11) NOT NULL COMMENT 'Id Tabla Departamento',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del Municipio de Colombia',
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Departamentos de Colombia';


-- -----------------------------------------------------
-- Table `acreditacion`.`documentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`documentacion` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`documentacion` (
  `id_tipoDocumentacion` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoDocumentacion`),
  INDEX `fk_documentacion_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_documentacion_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 652
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`documentacionlegal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`documentacionlegal` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`documentacionlegal` (
  `id_documentacionLegal` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id de la tabla Documentacion Legal',
  `registroEducativo` VARCHAR(1000) NOT NULL DEFAULT '0' COMMENT 'Si tiene o No Tiene Registro Educativo',
  `entidadRegistro` VARCHAR(1000) NOT NULL COMMENT 'Entidad quien registro el Registro Educativo',
  `numeroResolucion` VARCHAR(1000) NOT NULL COMMENT 'Numero de la Resolucion del Registro',
  `fechaResolucion` DATE NOT NULL COMMENT 'Fecha en la que se expide el Resgistro ',
  `departamentoResolucion` VARCHAR(1000) NOT NULL COMMENT 'Departamento donde se expide la resolucion',
  `municipioResolucion` VARCHAR(1000) NOT NULL COMMENT 'Municipio donde se expide la resolucion',
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizacion',
  PRIMARY KEY (`id_documentacionLegal`),
  INDEX `fk_documentacionLegal_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_documentacionLegal_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 387
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario # 2 de SIA Documentacion Legal.';


-- -----------------------------------------------------
-- Table `acreditacion`.`encuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`encuesta` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`encuesta` (
  `idencuesta` INT(11) NOT NULL AUTO_INCREMENT,
  `estrellas` INT(11) NOT NULL,
  `comentario` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idencuesta`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `acreditacion`.`estadoorganizaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`estadoorganizaciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`estadoorganizaciones` (
  `id_estadoOrganizacion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(1000) NOT NULL COMMENT 'Nombre del Estado Actual de la Organizacion: Inscrito, En Proceso, Finalizado, Acreditado, No Acreditado',
  `fechaUltimaActualizacion` DATETIME NULL DEFAULT NULL,
  `estadoAnterior` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Estado Anterior que tuvo la Organizacion, esto por si el usuario elimina la solicitud actual se devuelve el estado anterior',
  `fechaFinalizado` DATETIME NULL DEFAULT NULL,
  `tipoSolicitudAcreditado` VARCHAR(1000) NULL DEFAULT NULL,
  `motivoSolicitudAcreditado` VARCHAR(1000) NULL DEFAULT NULL,
  `modalidadSolicitudAcreditado` VARCHAR(1000) NULL DEFAULT NULL,
  `idSolicitudAcreditado` VARCHAR(1000) NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizacion',
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estadoOrganizacion`),
  INDEX `fk_estadoOrganizaciones_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_estadoOrganizaciones_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1150
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`historial` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`historial` (
  `id_historial` INT(11) NOT NULL AUTO_INCREMENT,
  `personeriaJuridica` VARCHAR(1000) NOT NULL,
  `nombresSeriesAsuntos` VARCHAR(1000) NOT NULL,
  `regional` VARCHAR(1000) NOT NULL,
  `fechaExtremaInicial` DATE NOT NULL,
  `fechaExtremaFinal` DATE NOT NULL,
  `caja` VARCHAR(1000) NULL DEFAULT NULL,
  `carpeta` VARCHAR(1000) NULL DEFAULT NULL,
  `tomo` VARCHAR(1000) NULL DEFAULT NULL,
  `otros` VARCHAR(1000) NULL DEFAULT NULL,
  `numeroFolios` VARCHAR(1000) NULL DEFAULT NULL,
  `soporte` VARCHAR(1000) NULL DEFAULT NULL,
  `observaciones` LONGTEXT NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_historial`))
ENGINE = InnoDB
AUTO_INCREMENT = 694
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`historialresoluciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`historialresoluciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`historialresoluciones` (
  `id_historialResoluciones` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaResolucionInicial` DATE NULL DEFAULT NULL,
  `fechaResolucionFinal` DATE NULL DEFAULT NULL,
  `añosResolucion` INT(11) NULL DEFAULT NULL,
  `resolucion` VARCHAR(1000) NULL DEFAULT NULL,
  `numeroResolucion` VARCHAR(1000) NULL DEFAULT NULL,
  `tipoResolucion` VARCHAR(1000) NULL DEFAULT '-',
  `historial_id_historial` INT(11) NOT NULL,
  PRIMARY KEY (`id_historialResoluciones`),
  INDEX `fk_historialResoluciones_historial1_idx` (`historial_id_historial` ASC) VISIBLE,
  CONSTRAINT `fk_historialResoluciones_historial1`
    FOREIGN KEY (`historial_id_historial`)
    REFERENCES `acreditacion`.`historial` (`id_historial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 736
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`historico_estado_informe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`historico_estado_informe` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`historico_estado_informe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `changed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `changed_by` INT(11) NOT NULL,
  `informeActividades_id_informeActividades` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historico_estado_informes_informeActividades1_idx` (`informeActividades_id_informeActividades` ASC) VISIBLE,
  CONSTRAINT `fk_historico_estado_informes_informeActividades1`
    FOREIGN KEY (`informeActividades_id_informeActividades`)
    REFERENCES `acreditacion`.`informeactividades` (`id_informeActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 536
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `acreditacion`.`informaciongeneral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`informaciongeneral` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`informaciongeneral` (
  `id_informacionGeneral` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id tabla informacion general',
  `tipoOrganizacion` VARCHAR(1000) NOT NULL COMMENT 'Tipo organizacion Select Option: Asociación\\nAsociación Mutual\\nCooperativa de Trabajo Asociado\\nCooperativa Especializada\\nCooperativa Integral\\nCooperativa Multiactiva\\nCorporación\\nEmpresa asociativa de trabajo\\nEmpresa Comunitaria\\nEmpresa de servicios en forma de administración pública\\nEmpresa Solidaria de Salud\\nFederación y Confederación\\nFondo de empleados\\nFundación\\nInstitución Universitaria\\nInstituciones auxiliares de Economía Solidaria\\nPrecooperativa',
  `direccionOrganizacion` VARCHAR(1000) NOT NULL COMMENT 'Direccion de la Organizacion',
  `nomDepartamentoUbicacion` VARCHAR(1000) NOT NULL COMMENT 'Nombre del departamento de la organizacion',
  `nomMunicipioNacional` VARCHAR(1000) NOT NULL COMMENT 'Nombre del municipio de la organizacion',
  `fax` VARCHAR(1000) NOT NULL COMMENT 'Numero de Fax - Telefono de la organizacion',
  `extension` VARCHAR(1000) NOT NULL DEFAULT 'No Tiene' COMMENT 'Si tiene alguna extension ',
  `urlOrganizacion` VARCHAR(1000) NOT NULL DEFAULT 'No Tiene' COMMENT 'La pagina web URL de la organizacion',
  `actuacionOrganizacion` VARCHAR(1000) NOT NULL COMMENT 'Actuacion de la Organizacion Select Option: Departamental\\nMunicipal\\nNacional\\nRegional',
  `tipoEducacion` VARCHAR(1000) NOT NULL COMMENT 'Tipo de Educacion de la Organizacion Select Option: Educacion para el trabajo y el desarrollo humano\\nFormal\\nInformal',
  `numCedulaCiudadaniaPersona` VARCHAR(1000) NOT NULL COMMENT 'Numero de Cedula del Representante Legal',
  `presentacionInstitucional` LONGTEXT NULL DEFAULT NULL COMMENT 'Presentacion de la Organizacion Texto',
  `objetoSocialEstatutos` LONGTEXT NULL DEFAULT NULL COMMENT 'Objeto Social de la Organizacion Texto',
  `mision` LONGTEXT NULL DEFAULT NULL COMMENT 'MIsion de la Organizacion Texto',
  `vision` LONGTEXT NULL DEFAULT NULL COMMENT 'Vision de la Organizacion Texto',
  `principios` LONGTEXT NULL DEFAULT NULL COMMENT 'Principios de la Organizacion Texto',
  `fines` LONGTEXT NULL DEFAULT NULL COMMENT 'Fines de la Organizacion Texto',
  `portafolio` LONGTEXT NULL DEFAULT NULL COMMENT 'Portafolio de la Organizacion Texto',
  `otros` LONGTEXT NULL DEFAULT NULL COMMENT 'Otros Puede ingresar otra cosa dependiendo del caso Texto',
  `fecha` DATETIME NOT NULL COMMENT 'Fecha en la se que registro la infomacion',
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK de la Id_Organizacion',
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_informacionGeneral`),
  INDEX `fk_informacionGeneral_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_informacionGeneral_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 345
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario # 1 de SIA Informacion General.';


-- -----------------------------------------------------
-- Table `acreditacion`.`jornadasactualizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`jornadasactualizacion` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`jornadasactualizacion` (
  `id_jornadasActualizacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Jornadas de Actualziacion',
  `asistio` VARCHAR(1000) NULL DEFAULT NULL,
  `fechaAsistencia` DATE NULL DEFAULT '1900-01-01' COMMENT 'Fecha de asistencia',
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizacion',
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_jornadasActualizacion`),
  INDEX `fk_jornadasActualizacion_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_jornadasActualizacion_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 964
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario #5 de SIA';


-- -----------------------------------------------------
-- Table `acreditacion`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`municipios` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`municipios` (
  `id_municipio` INT(11) NOT NULL COMMENT 'Id Tabla Municipio',
  `nombreMunicipio` VARCHAR(45) NOT NULL COMMENT 'Nombre del Municipio de Colombia',
  `departamentos_id_departamento` INT(11) NOT NULL COMMENT 'Fk Id_Departamento',
  PRIMARY KEY (`id_municipio`),
  INDEX `fk_municipios_departamentos1_idx` (`departamentos_id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_municipios_departamentos1`
    FOREIGN KEY (`departamentos_id_departamento`)
    REFERENCES `acreditacion`.`departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla de Municipios de Colombia';


-- -----------------------------------------------------
-- Table `acreditacion`.`nits_db`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`nits_db` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`nits_db` (
  `idnits_db` INT(11) NOT NULL AUTO_INCREMENT,
  `numNIT` VARCHAR(1000) NULL DEFAULT NULL,
  `nombreOrganizacion` VARCHAR(1000) NULL DEFAULT NULL,
  `numeroResolucion` VARCHAR(1000) NULL DEFAULT NULL,
  `fechaFinalizacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idnits_db`))
ENGINE = InnoDB
AUTO_INCREMENT = 535
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `acreditacion`.`notificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`notificaciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`notificaciones` (
  `id_notificaciones` INT(11) NOT NULL AUTO_INCREMENT,
  `tituloNotificacion` VARCHAR(1000) NOT NULL COMMENT 'Titulo de la Notificacion',
  `descripcionNotificacion` VARCHAR(1000) NOT NULL COMMENT 'Descripcion de la Notificacion',
  `fechaNotificacion` DATETIME NOT NULL COMMENT 'Fecha de guardado de la Notificacion',
  `quienEnvia` VARCHAR(1000) NOT NULL COMMENT 'Quien envia la notificacion',
  `quienRecibe` VARCHAR(1000) NOT NULL COMMENT 'Quien Recibe la notificacion',
  `isRead` CHAR(1) NOT NULL COMMENT 'Si se leyo la notificacion es 0, Si no se leyo 1',
  `tipoUsuario` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Tipo de Usuario a Enviar',
  PRIMARY KEY (`id_notificaciones`))
ENGINE = InnoDB
AUTO_INCREMENT = 12755
DEFAULT CHARACTER SET = utf8
COMMENT = 'Las notificaciones internas de la aplicación';


-- -----------------------------------------------------
-- Table `acreditacion`.`observaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`observaciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`observaciones` (
  `id_observacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Observaciones',
  `idForm` LONGTEXT NULL DEFAULT NULL COMMENT 'Id del Formulario',
  `keyForm` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Key del Formulario',
  `valueForm` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Value del Formulario',
  `observacion` LONGTEXT NULL DEFAULT NULL COMMENT 'Observacion del Formulario',
  `fechaObservacion` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de la Observacion',
  `fechaVencimiento` DATETIME NULL DEFAULT NULL,
  `numeroRevision` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Numero de la Revision',
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizacion',
  `valida` INT(11) NULL DEFAULT '0',
  `realizada` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_observacion`),
  INDEX `fk_observaciones_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_observaciones_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12229
DEFAULT CHARACTER SET = utf8
COMMENT = 'Observaciones que se hacen a los Formularios que el usuario diligencio';


-- -----------------------------------------------------
-- Table `acreditacion`.`observaciones_informe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`observaciones_informe` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`observaciones_informe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `administradores_id_administrador` INT(11) NOT NULL,
  `informeActividades_id_informeActividades` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_observaciones_informe_administradores1_idx` (`administradores_id_administrador` ASC) VISIBLE,
  INDEX `fk_observaciones_informe_informeActividades1_idx` (`informeActividades_id_informeActividades` ASC) VISIBLE,
  CONSTRAINT `fk_observaciones_informe_administradores1`
    FOREIGN KEY (`administradores_id_administrador`)
    REFERENCES `acreditacion`.`administradores` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observaciones_informe_informeActividades1`
    FOREIGN KEY (`informeActividades_id_informeActividades`)
    REFERENCES `acreditacion`.`informeactividades` (`id_informeActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `acreditacion`.`observacionesdocente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`observacionesdocente` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`observacionesdocente` (
  `id_observacionesDocente` INT(11) NOT NULL AUTO_INCREMENT,
  `observacionesDocente` LONGTEXT NULL DEFAULT NULL,
  `fechaObservacion` DATETIME NULL DEFAULT NULL,
  `docentes_id_docente` INT(11) NOT NULL,
  PRIMARY KEY (`id_observacionesDocente`),
  INDEX `fk_observacionesDocente_docentes1_idx` (`docentes_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_observacionesDocente_docentes1`
    FOREIGN KEY (`docentes_id_docente`)
    REFERENCES `acreditacion`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `acreditacion`.`opciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`opciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`opciones` (
  `id_opcion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Opciones',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre de la Opcion: Imagen Texto ',
  `valor` LONGTEXT NOT NULL COMMENT 'Valor que se le da al Nombre',
  PRIMARY KEY (`id_opcion`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COMMENT = 'Opciones del Sistema de Sia';


-- -----------------------------------------------------
-- Table `acreditacion`.`organizacioneshistorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`organizacioneshistorial` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`organizacioneshistorial` (
  `id_organizacionHistorial` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Registro de la Organizacion',
  `nombreOrganizacion` VARCHAR(1000) NOT NULL COMMENT 'Nombre de la Organizacion',
  `numNIT` VARCHAR(1000) NOT NULL COMMENT 'Numero NIT de la Organizacion',
  `sigla` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'Sigla de la organizacion',
  `primerNombreRepLegal` VARCHAR(1000) NOT NULL COMMENT 'Primer Nombre del Representante Legal',
  `segundoNombreRepLegal` VARCHAR(1000) NULL DEFAULT 'No Tiene' COMMENT 'Segundo Nombre del Representante Legal',
  `primerApellidoRepLegal` VARCHAR(1000) NOT NULL COMMENT 'Primer Apellido del Representante Legal',
  `segundoApellidoRepLegal` VARCHAR(1000) NULL DEFAULT 'No Tiene' COMMENT 'Segundo Apellido del Representante Legal',
  `direccionCorreoElectronicoOrganizacion` VARCHAR(1000) NOT NULL COMMENT 'Direccion de Correo Electronico de Contacto de la organizacion',
  `direccionCorreoElectronicoRepLegal` VARCHAR(1000) NOT NULL COMMENT 'Direccion de Correo Electronico de Contacto del representante legal',
  PRIMARY KEY (`id_organizacionHistorial`))
ENGINE = InnoDB
AUTO_INCREMENT = 740
DEFAULT CHARACTER SET = utf8
COMMENT = 'Primer registro de las organizaciones';


-- -----------------------------------------------------
-- Table `acreditacion`.`planmejoramiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`planmejoramiento` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`planmejoramiento` (
  `id_planMejoramiento` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcionMejora` LONGTEXT NOT NULL,
  `fechaMejora` DATE NOT NULL,
  `cumple` CHAR(1) NOT NULL,
  `observaciones` LONGTEXT NULL DEFAULT NULL,
  `visitas_id_visitas` INT(11) NOT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  PRIMARY KEY (`id_planMejoramiento`),
  INDEX `fk_planMejoramiento_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_planMejoramiento_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`programasavalar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`programasavalar` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`programasavalar` (
  `id_programasAvalar` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Programas a Avalar',
  `nombrePrograma` LONGTEXT NOT NULL COMMENT 'Nombre del Programa a Avalar',
  `objetivos` LONGTEXT NOT NULL COMMENT 'Obejtivos del Programa a Avalar',
  `metodologia` LONGTEXT NOT NULL COMMENT 'Metodologia del Programa a Avalar',
  `contenidosPlanteados` LONGTEXT NOT NULL COMMENT 'Contenido Planteado al Programa a Avalar',
  `materialDidactico` LONGTEXT NOT NULL COMMENT 'Material Didactico que usa el Programa',
  `bibliografia` LONGTEXT NOT NULL COMMENT 'Bibliografia que usa el Programa a Avalar',
  `intensidadHoraria` LONGTEXT NOT NULL COMMENT 'Intesidad horaria que tiene el Programa a Avalar',
  `evaluacion` LONGTEXT NOT NULL COMMENT 'Como se evalua el Programa a Avalar',
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizaciones',
  PRIMARY KEY (`id_programasAvalar`),
  INDEX `fk_programasAvalar_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_programasAvalar_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 93
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario #8 SIA';


-- -----------------------------------------------------
-- Table `acreditacion`.`programasavaleconomia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`programasavaleconomia` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`programasavaleconomia` (
  `id_programasAvalEconomia` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Programas Aval Economia Solidaria',
  `objetivos` LONGTEXT NOT NULL COMMENT 'Objetivos del Programa',
  `metodologia` LONGTEXT NOT NULL COMMENT 'Metodologia del Programa',
  `materialDidactico` LONGTEXT NOT NULL COMMENT 'Material Didactivo que usa el Programa',
  `bibliografia` LONGTEXT NOT NULL COMMENT 'Bibliografia del Programa',
  `duracionCurso` LONGTEXT NOT NULL COMMENT 'Duracion del curso Programa',
  `antecedentesAspectos` LONGTEXT NULL DEFAULT NULL,
  `diferencias` LONGTEXT NULL DEFAULT NULL,
  `regulacionJuridica` LONGTEXT NULL DEFAULT NULL,
  `desarrolloSocioempresarial` LONGTEXT NULL DEFAULT NULL,
  `legislacionTributaria` LONGTEXT NULL DEFAULT NULL,
  `administracionTrabajo` LONGTEXT NULL DEFAULT NULL,
  `regimenesTrabajo` LONGTEXT NULL DEFAULT NULL,
  `manejoSeguridad` LONGTEXT NULL DEFAULT NULL,
  `inspeccionVigilancia` LONGTEXT NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL DEFAULT '0' COMMENT 'FK Id_Organizacion',
  PRIMARY KEY (`id_programasAvalEconomia`),
  INDEX `fk_programasAvalEconomia_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_programasAvalEconomia_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario #7 SIA';


-- -----------------------------------------------------
-- Table `acreditacion`.`registroeducativoprogramas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`registroeducativoprogramas` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`registroeducativoprogramas` (
  `id_registroEducativoPro` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id tabla Registro educativo',
  `tipoEducacion` VARCHAR(255) NOT NULL,
  `fechaResolucion` DATE NOT NULL COMMENT 'Fecha en la que se expide la resolucion',
  `numeroResolucion` INT(11) NOT NULL COMMENT 'Numero de la resolucion',
  `nombrePrograma` VARCHAR(1000) NOT NULL COMMENT 'Nombre del Programa Texto',
  `objetoResolucion` LONGTEXT NOT NULL COMMENT 'Objeto de la Resolucion',
  `entidadResolucion` VARCHAR(1000) NOT NULL COMMENT 'Entidad que expidio la resolucion Select Option: Ministerio De Educación\\nSecretaria De Educación Departamental\\nSecretaria De Educación Municipal',
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizaciones',
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_registroEducativoPro`),
  INDEX `fk_registroEducativoProgramas_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_registroEducativoProgramas_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 191
DEFAULT CHARACTER SET = utf8
COMMENT = 'Formulario # 3 de SIA Registro Educativo de Programas.';


-- -----------------------------------------------------
-- Table `acreditacion`.`registrotelefonico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`registrotelefonico` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`registrotelefonico` (
  `id_registroTelefonico` INT(11) NOT NULL AUTO_INCREMENT,
  `funcionario` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `tipoLlamada` VARCHAR(45) NOT NULL,
  `tipoComunicacion` VARCHAR(45) NOT NULL,
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL,
  `duracion` VARCHAR(225) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  `administradores_id_administrador` INT(11) NOT NULL,
  PRIMARY KEY (`id_registroTelefonico`),
  INDEX `fk_registroTefefonico_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  INDEX `fk_registroTefefonico_administradores1_idx` (`administradores_id_administrador` ASC) VISIBLE,
  CONSTRAINT `fk_registroTefefonico_administradores1`
    FOREIGN KEY (`administradores_id_administrador`)
    REFERENCES `acreditacion`.`administradores` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registroTefefonico_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`registrotelefonico_historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`registrotelefonico_historico` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`registrotelefonico_historico` (
  `id_registroTelefonico` INT(11) NOT NULL AUTO_INCREMENT,
  `telefonicoNombre` LONGTEXT NULL DEFAULT NULL,
  `telefonicoApellidos` LONGTEXT NULL DEFAULT NULL,
  `telefonicoCedula` LONGTEXT NULL DEFAULT NULL,
  `telefonicoNit` LONGTEXT NULL DEFAULT NULL,
  `telefonicoTipoPersona` LONGTEXT NULL DEFAULT NULL,
  `telefonicoGenero` LONGTEXT NULL DEFAULT NULL,
  `telefonicoMunicipio` LONGTEXT NULL DEFAULT NULL,
  `telefonicoDepartamento` LONGTEXT NULL DEFAULT NULL,
  `telefonicoNumeroContacto` LONGTEXT NULL DEFAULT NULL,
  `telefonicoCorreoContacto` LONGTEXT NULL DEFAULT NULL,
  `telefonicoNombreOrganizacion` LONGTEXT NULL DEFAULT NULL,
  `telefonicoTipoOrganizacion` LONGTEXT NULL DEFAULT NULL,
  `telefonicoTemaConsulta` LONGTEXT NULL DEFAULT NULL,
  `telefonicoDescripcionConsulta` LONGTEXT NULL DEFAULT NULL,
  `telefonicoTipoSolicitud` LONGTEXT NULL DEFAULT NULL,
  `telefonicoCanalRecepcion` LONGTEXT NULL DEFAULT NULL,
  `telefonicoCanalRespuesta` LONGTEXT NULL DEFAULT NULL,
  `telefonicoFecha` LONGTEXT NULL DEFAULT NULL,
  `telefonicoDuracion` LONGTEXT NULL DEFAULT NULL,
  `telefonicoHora` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_registroTelefonico`))
ENGINE = InnoDB
AUTO_INCREMENT = 838
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `acreditacion`.`resoluciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`resoluciones` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`resoluciones` (
  `id_resoluciones` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaResolucionInicial` DATE NULL DEFAULT NULL,
  `fechaResolucionFinal` DATE NULL DEFAULT NULL,
  `anosResolucion` INT(11) NULL DEFAULT NULL,
  `resolucion` VARCHAR(1000) NULL DEFAULT NULL,
  `numeroResolucion` VARCHAR(1000) NULL DEFAULT NULL,
  `cursoAprobado` VARCHAR(1000) NULL DEFAULT NULL,
  `modalidadAprobada` VARCHAR(1000) NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NULL DEFAULT NULL,
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_resoluciones`),
  INDEX `fk_resoluciones_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 533
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`visitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`visitas` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`visitas` (
  `id_visitas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreOrganizacionVisita` VARCHAR(1000) NOT NULL,
  `fechaVisita` DATE NOT NULL,
  `horaVisita` VARCHAR(1000) NOT NULL,
  `usuarioVisita` VARCHAR(1000) NOT NULL,
  `terminada` CHAR(1) NOT NULL DEFAULT '0',
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  PRIMARY KEY (`id_visitas`),
  INDEX `fk_visitas_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_visitas_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`seguimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`seguimiento` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`seguimiento` (
  `id_seguimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `certificadoExistencia` CHAR(1) NOT NULL,
  `matriculaMercantil` CHAR(1) NOT NULL,
  `actividadesEducacion` CHAR(1) NOT NULL,
  `domicilio` CHAR(1) NOT NULL,
  `datosRepLegal` CHAR(1) NOT NULL,
  `fechaVigenciaCertificado` CHAR(1) NOT NULL,
  `metodologiaAcreditada` CHAR(1) NOT NULL,
  `materialDidactico` CHAR(1) NOT NULL,
  `contenidosEducativo` CHAR(1) NOT NULL,
  `socializacionConceptos` CHAR(1) NOT NULL,
  `contextoSocioEconomico` CHAR(1) NOT NULL,
  `tiposOrganizacionesSolidarias` CHAR(1) NOT NULL,
  `entesControlyApoyo` CHAR(1) NOT NULL,
  `avalCursos` CHAR(1) NOT NULL,
  `contenidosProgramas` CHAR(1) NOT NULL,
  `otrosProgramas` CHAR(1) NOT NULL,
  `actualizacionDatosUnidad` CHAR(1) NOT NULL,
  `suministroInformacionVisitas` CHAR(1) NOT NULL,
  `entregaInformesActividades` CHAR(1) NOT NULL,
  `docentesHabilitados` CHAR(1) NOT NULL,
  `archivoHistoricoEducacion` CHAR(1) NOT NULL,
  `cursosSolidaridadEducativa` CHAR(1) NOT NULL,
  `subcontratacionTerceros` CHAR(1) NOT NULL,
  `cotejoCertificacionesCurso` CHAR(1) NOT NULL,
  `actualizacionHojaVidaDocentes` CHAR(1) NOT NULL,
  `hallazgos` LONGTEXT NOT NULL,
  `visitas_id_visitas` INT(11) NOT NULL,
  PRIMARY KEY (`id_seguimiento`),
  INDEX `fk_seguimiento_visitas1_idx` (`visitas_id_visitas` ASC) VISIBLE,
  CONSTRAINT `fk_seguimiento_visitas1`
    FOREIGN KEY (`visitas_id_visitas`)
    REFERENCES `acreditacion`.`visitas` (`id_visitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`seguimientosimple`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`seguimientosimple` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`seguimientosimple` (
  `id_seguimientoSimple` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaSeguimiento` DATE NOT NULL,
  `descripcionSeguimiento` VARCHAR(1000) NOT NULL,
  `respuestaSeguimiento` VARCHAR(1000) NULL DEFAULT NULL,
  `cumpleSeguimiento` CHAR(1) NOT NULL DEFAULT '0',
  `nombreOrganizacion` VARCHAR(1000) NOT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL,
  PRIMARY KEY (`id_seguimientoSimple`),
  INDEX `fk_seguimientoSimple_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_seguimientoSimple_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `acreditacion`.`session_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`session_log` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`session_log` (
  `id_session_log` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id se Session Log',
  `nombre_usuario` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Nombre del usuario en log',
  `usuario_id` INT(11) NULL DEFAULT NULL COMMENT 'Id del usuario en log',
  `accion` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Accion que realizo el usuario',
  `fecha` DATETIME NULL DEFAULT NULL COMMENT 'Cuando realizo la accion',
  `usuario_ip` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Ip del usuario',
  `usuario_ip_proxy` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Ip del usuario si usa proxy',
  `user_agent` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Agente de donde esta haciendo las acciones',
  PRIMARY KEY (`id_session_log`))
ENGINE = InnoDB
AUTO_INCREMENT = 91325
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`solicitudes` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`solicitudes` (
  `id_solicitud` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Tabla Solicitudes',
  `numeroSolicitudes` INT(11) NULL DEFAULT '0' COMMENT 'Numero de Solicitudes que hace la Organizacion',
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `numeroRevisiones` INT(11) NOT NULL DEFAULT '0' COMMENT 'Numero de las revisiones de la solicitud',
  `fechaUltimaRevision` DATETIME NULL DEFAULT NULL,
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_Organizacion',
  `idSolicitud` VARCHAR(45) NULL DEFAULT NULL,
  `asignada` VARCHAR(45) NULL DEFAULT 'SIN ASIGNAR',
  `fechaAsignacion` DATETIME NULL DEFAULT NULL,
  `asignada_por` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `fk_solicitudes_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_solicitudes_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1150
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla de numero de solicitudes';


-- -----------------------------------------------------
-- Table `acreditacion`.`tiposcursoinformes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`tiposcursoinformes` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`tiposcursoinformes` (
  `id_tiposCursoInformes` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id_tiposCursoInformes`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acreditacion`.`tiposolicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`tiposolicitud` ;

CREATE TABLE IF NOT EXISTS `acreditacion`.`tiposolicitud` (
  `id_tipoSolicitud` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id tabla tipo solicitud',
  `tipoSolicitud` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Tipo de Solicitud Radio Button: Acreditacion Primera Vez, Renovacion de acreditacion, Actualziacion de Datos',
  `motivoSolicitud` VARCHAR(1000) NOT NULL COMMENT 'Motivo Solicitud Radio Button: Acreditación Curso Basico de Economia Solidaria.\\nAcreditación, Aval de Trabajo Asociado.\\nAcreditación, Aval a otros Programas.\\nAcreditación, Aval de Trabajo Asociado, Aval a otros Programas. (Todas)\\n ',
  `modalidadSolicitud` VARCHAR(1000) NOT NULL COMMENT 'Modalidad Solicitud Radio Button: Virtual\\nPresencial\\nVirtual y Presencial',
  `idSolicitud` VARCHAR(1000) NOT NULL COMMENT 'Id unico de la Solicitud Creada',
  `organizaciones_id_organizacion` INT(11) NOT NULL COMMENT 'FK Id_ Organizaciones',
  `motivosSolicitud` JSON NULL DEFAULT NULL,
  `modalidadesSolicitud` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoSolicitud`),
  INDEX `fk_tipoSolicitud_organizaciones1_idx` (`organizaciones_id_organizacion` ASC) VISIBLE,
  CONSTRAINT `fk_tipoSolicitud_organizaciones1`
    FOREIGN KEY (`organizaciones_id_organizacion`)
    REFERENCES `acreditacion`.`organizaciones` (`id_organizacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 806
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tipo de la Solicitud del Usuario';

USE `acreditacion` ;

-- -----------------------------------------------------
-- Placeholder table for view `acreditacion`.`vieworganizacionesacreditadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acreditacion`.`vieworganizacionesacreditadas` (`nombreOrganizacion` INT, `numNIT` INT, `tipoOrganizacion` INT, `nomDepartamentoUbicacion` INT, `nomMunicipioNacional` INT);

-- -----------------------------------------------------
-- Placeholder table for view `acreditacion`.`vieworganizacionesavaladas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acreditacion`.`vieworganizacionesavaladas` (`nombreOrganizacion` INT, `numNIT` INT, `tipoOrganizacion` INT, `nomDepartamentoUbicacion` INT, `nomMunicipioNacional` INT);

-- -----------------------------------------------------
-- Placeholder table for view `acreditacion`.`vieworganizacionesbasico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acreditacion`.`vieworganizacionesbasico` (`nombreOrganizacion` INT, `numNIT` INT, `tipoOrganizacion` INT, `nomDepartamentoUbicacion` INT, `nomMunicipioNacional` INT);

-- -----------------------------------------------------
-- Placeholder table for view `acreditacion`.`vieworganizacionesvirtual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acreditacion`.`vieworganizacionesvirtual` (`nombreOrganizacion` INT, `numNIT` INT, `tipoOrganizacion` INT, `nomDepartamentoUbicacion` INT, `nomMunicipioNacional` INT, `modalidadSolicitudAcreditado` INT);

-- -----------------------------------------------------
-- View `acreditacion`.`vieworganizacionesacreditadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`vieworganizacionesacreditadas`;
DROP VIEW IF EXISTS `acreditacion`.`vieworganizacionesacreditadas` ;
USE `acreditacion`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `acreditacion`.`vieworganizacionesacreditadas` AS select `acreditacion`.`organizaciones`.`nombreOrganizacion` AS `nombreOrganizacion`,`acreditacion`.`organizaciones`.`numNIT` AS `numNIT`,`acreditacion`.`informaciongeneral`.`tipoOrganizacion` AS `tipoOrganizacion`,`acreditacion`.`informaciongeneral`.`nomDepartamentoUbicacion` AS `nomDepartamentoUbicacion`,`acreditacion`.`informaciongeneral`.`nomMunicipioNacional` AS `nomMunicipioNacional` from ((`acreditacion`.`organizaciones` join `acreditacion`.`estadoorganizaciones` on((`acreditacion`.`estadoorganizaciones`.`organizaciones_id_organizacion` = `acreditacion`.`organizaciones`.`id_organizacion`))) join `acreditacion`.`informaciongeneral` on((`acreditacion`.`informaciongeneral`.`organizaciones_id_organizacion` = `acreditacion`.`organizaciones`.`id_organizacion`))) where (`acreditacion`.`estadoorganizaciones`.`nombre` = 'Acreditado');

-- -----------------------------------------------------
-- View `acreditacion`.`vieworganizacionesavaladas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`vieworganizacionesavaladas`;
DROP VIEW IF EXISTS `acreditacion`.`vieworganizacionesavaladas` ;
USE `acreditacion`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `acreditacion`.`vieworganizacionesavaladas` AS select `acreditacion`.`organizaciones`.`nombreOrganizacion` AS `nombreOrganizacion`,`acreditacion`.`organizaciones`.`numNIT` AS `numNIT`,`acreditacion`.`informaciongeneral`.`tipoOrganizacion` AS `tipoOrganizacion`,`acreditacion`.`informaciongeneral`.`nomDepartamentoUbicacion` AS `nomDepartamentoUbicacion`,`acreditacion`.`informaciongeneral`.`nomMunicipioNacional` AS `nomMunicipioNacional` from ((`acreditacion`.`organizaciones` join `acreditacion`.`estadoorganizaciones` on((`acreditacion`.`estadoorganizaciones`.`organizaciones_id_organizacion` = `acreditacion`.`organizaciones`.`id_organizacion`))) join `acreditacion`.`informaciongeneral` on((`acreditacion`.`informaciongeneral`.`organizaciones_id_organizacion` = `acreditacion`.`organizaciones`.`id_organizacion`))) where ((`acreditacion`.`estadoorganizaciones`.`nombre` = 'Acreditado') and (`acreditacion`.`estadoorganizaciones`.`motivoSolicitudAcreditado` = 'Acreditación, Aval de Trabajo Asociado'));

-- -----------------------------------------------------
-- View `acreditacion`.`vieworganizacionesbasico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`vieworganizacionesbasico`;
DROP VIEW IF EXISTS `acreditacion`.`vieworganizacionesbasico` ;
USE `acreditacion`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `acreditacion`.`vieworganizacionesbasico` AS select `acreditacion`.`organizaciones`.`nombreOrganizacion` AS `nombreOrganizacion`,`acreditacion`.`organizaciones`.`numNIT` AS `numNIT`,`acreditacion`.`informaciongeneral`.`tipoOrganizacion` AS `tipoOrganizacion`,`acreditacion`.`informaciongeneral`.`nomDepartamentoUbicacion` AS `nomDepartamentoUbicacion`,`acreditacion`.`informaciongeneral`.`nomMunicipioNacional` AS `nomMunicipioNacional` from ((`acreditacion`.`organizaciones` join `acreditacion`.`estadoorganizaciones` on((`acreditacion`.`estadoorganizaciones`.`organizaciones_id_organizacion` = `acreditacion`.`organizaciones`.`id_organizacion`))) join `acreditacion`.`informaciongeneral` on((`acreditacion`.`informaciongeneral`.`organizaciones_id_organizacion` = `acreditacion`.`organizaciones`.`id_organizacion`))) where ((`acreditacion`.`estadoorganizaciones`.`nombre` = 'Acreditado') and (`acreditacion`.`estadoorganizaciones`.`motivoSolicitudAcreditado` = 'Acreditación Curso Basico de Economia Solidaria'));

-- -----------------------------------------------------
-- View `acreditacion`.`vieworganizacionesvirtual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acreditacion`.`vieworganizacionesvirtual`;
DROP VIEW IF EXISTS `acreditacion`.`vieworganizacionesvirtual` ;
USE `acreditacion`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `acreditacion`.`vieworganizacionesvirtual` AS select `acreditacion`.`organizaciones`.`nombreOrganizacion` AS `nombreOrganizacion`,`acreditacion`.`organizaciones`.`numNIT` AS `numNIT`,`acreditacion`.`informaciongeneral`.`tipoOrganizacion` AS `tipoOrganizacion`,`acreditacion`.`informaciongeneral`.`nomDepartamentoUbicacion` AS `nomDepartamentoUbicacion`,`acreditacion`.`informaciongeneral`.`nomMunicipioNacional` AS `nomMunicipioNacional`,`acreditacion`.`estadoorganizaciones`.`modalidadSolicitudAcreditado` AS `modalidadSolicitudAcreditado` from ((`acreditacion`.`organizaciones` join `acreditacion`.`estadoorganizaciones` on((`acreditacion`.`estadoorganizaciones`.`organizaciones_id_organizacion` = `acreditacion`.`organizaciones`.`id_organizacion`))) join `acreditacion`.`informaciongeneral` on((`acreditacion`.`informaciongeneral`.`organizaciones_id_organizacion` = `acreditacion`.`organizaciones`.`id_organizacion`))) where (((`acreditacion`.`estadoorganizaciones`.`nombre` = 'Acreditado') and (`acreditacion`.`estadoorganizaciones`.`modalidadSolicitudAcreditado` = 'Virtual')) or (`acreditacion`.`estadoorganizaciones`.`modalidadSolicitudAcreditado` = 'Virtual y Presencial'));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
